export type Post = { title: string; href: string };

export const POSTS: Post[] = [
  { title: "가리산 자연휴양림", href: "/posts/002_가리산 자연휴양림.html" },
  { title: "가리왕산 자연휴양림", href: "/posts/001_가리왕산자연휴양림.html" },
  { title: "간월자연휴양림", href: "/posts/003_간월자연휴양림.html" },
  { title: "갈모봉 자연휴양림", href: "/posts/004_갈모봉 자연휴양림.html" },
  { title: "강씨봉자연휴양림", href: "/posts/006_강씨봉자연휴양림.html" },
  { title: "강원숲체험장", href: "/posts/210_강원숲체험장.html" },
  { title: "강화자연휴양림", href: "/posts/008_강화자연휴양림.html" },
  { title: "갯골자연휴양림", href: "/posts/009_갯골자연휴양림.html" },
  { title: "거제자연휴양림", href: "/posts/010_거제자연휴양림.html" },
  { title: "거창산림레포츠파크", href: "/posts/207_거창산림레포츠파크.html" },
  { title: "거창항노화힐링랜드", href: "/posts/011_거창항노화힐링랜드.html" },
  { title: "검마산 자연휴양림", href: "/posts/208_검마산 자연휴양림.html" },
  { title: "검봉산 자연휴양림", href: "/posts/209_검봉산 자연휴양림.html" },
  { title: "계명산자연휴양림", href: "/posts/012_계명산자연휴양림.html" },
  { title: "고대산 자연휴양림", href: "/posts/013_고대산 자연휴양림.html" },
  { title: "고산자연휴양림", href: "/posts/015_고산자연휴양림.html" },
  { title: "공주산림휴양마을", href: "/posts/016_공주산림휴양마을.html" },
  { title: "광양백운산자연휴양림", href: "/posts/205_광양백운산자연휴양림.html" },
  { title: "광치자연휴양림", href: "/posts/017_광치자연휴양림.html" },
  { title: "교래자연휴양림", href: "/posts/206_교래자연휴양림.html" },
  { title: "구름산산림욕장", href: "/posts/018_구름산산림욕장.html" },
  { title: "구수곡자연휴양림", href: "/posts/019_구수곡자연휴양림.html" },
  { title: "구재봉자연휴양림", href: "/posts/020_구재봉자연휴양림.html" },
  { title: "국망봉자연휴양림", href: "/posts/021_국망봉자연휴양림.html" },
  { title: "군위장곡자연휴양림", href: "/posts/022_군위장곡자연휴양림.html" },
  { title: "금강자연휴양림", href: "/posts/023_금강자연휴양림.html" },
  { title: "금봉자연휴양림", href: "/posts/024_금봉자연휴양림.html" },
  { title: "금산 자연휴양림", href: "/posts/025_금산자연휴양림.html" },
  { title: "금산산림문화타운(남이자연휴양림)", href: "/posts/026_금산산림문화타운(남이자연휴양림).html" },
  { title: "금원산자연휴양림", href: "/posts/027_금원산자연휴양림.html" },
  { title: "기찬자연휴양림", href: "/posts/028_기찬자연휴양림.html" },
  { title: "김제 선암자연휴양림", href: "/posts/204_김제 선암자연휴양림.html" },
  { title: "김천숲속야영장", href: "/posts/202_김천숲속야영장.html" },
  { title: "낙안민속 자연휴양림", href: "/posts/203_낙안민속 자연휴양림.html" },
  { title: "남원자연휴양림", href: "/posts/029_남원자연휴양림.html" },
  { title: "남해편백 자연휴양림", href: "/posts/030_남해편백 자연휴양림.html" },
  { title: "내장산자연휴양림", href: "/posts/033_내장산 자연휴양림.html" },
  { title: "달음산 자연휴양림", href: "/posts/201_달음산 자연휴양림.html" },
  { title: "대관령 자연휴양림", href: "/posts/036_대관령 자연휴양림.html" },
  { title: "대봉산자연휴양림", href: "/posts/031_대봉산자연휴양림.html" },
  { title: "대봉캠핑랜드", href: "/posts/032_대봉캠핑랜드.html" },
  { title: "대야산 자연휴양림", href: "/posts/039_대야산 자연휴양림.html" },
  { title: "대운산자연휴양림", href: "/posts/040_대운산자연휴양림.html" },
  { title: "덕원자연휴양림", href: "/posts/034_덕원자연휴양림.html" },
  { title: "덕유산 자연휴양림", href: "/posts/200_덕유산 자연휴양림.html" },
  { title: "덕적도 자연휴양림", href: "/posts/199_덕적도 자연휴양림.html" },
  { title: "데미샘자연휴양림", href: "/posts/035_데미샘자연휴양림.html" },
  { title: "독용산성자연휴양림", href: "/posts/044_독용산성자연휴양림.html" },
  { title: "동강전망자연휴양림", href: "/posts/037_동강전망자연휴양림.html" },
  { title: "동두천자연휴양림", href: "/posts/038_동두천자연휴양림.html" },
  { title: "두릉산자연휴양림", href: "/posts/223_두릉산자연휴양림.html" },
  { title: "두타산 자연휴양림(평창)", href: "/posts/198_두타산 자연휴양림(평창).html" },
  { title: "만수산자연휴양림", href: "/posts/041_만수산자연휴양림.html" },
  { title: "만인산자연휴양림", href: "/posts/042_만인산자연휴양림.html" },
  { title: "망경대산자연휴양림", href: "/posts/043_망경대산자연휴양림.html" },
  { title: "무등산편백자연휴양림", href: "/posts/195_무등산편백자연휴양림.html" },
  { title: "무봉산 자연휴양림", href: "/posts/196_무봉산 자연휴양림.html" },
  { title: "무의도 자연휴양림", href: "/posts/197_무의도 자연휴양림.html" },
  { title: "무주향로산자연휴양림", href: "/posts/045_무주향로산자연휴양림.html" },
  { title: "문성자연휴양림", href: "/posts/046_문성자연휴양림.html" },
  { title: "문수산자연휴양림", href: "/posts/047_문수산자연휴양림.html" },
  { title: "미숭산자연휴양림", href: "/posts/048_미숭산자연휴양림.html" },
  { title: "미천골 자연휴양림", href: "/posts/066_미천골자연휴양림.html" },
  { title: "민주지산자연휴양림", href: "/posts/068_민주지산자연휴양림.html" },
  { title: "밀양 도래재자연휴양림", href: "/posts/049_밀양 도래재자연휴양림.html" },
  { title: "박달재자연휴양림", href: "/posts/050_박달재자연휴양림.html" },
  { title: "반딧불 자연휴양림", href: "/posts/051_반딧불 자연휴양림.html" },
  { title: "방장산 자연휴양림", href: "/posts/052_방장산 자연휴양림.html" },
  { title: "방태산 자연휴양림", href: "/posts/194_방태산 자연휴양림.html" },
  { title: "방화동자연휴양림", href: "/posts/053_방화동자연휴양림.html" },
  { title: "백아산자연휴양림", href: "/posts/054_백아산자연휴양림.html" },
  { title: "백야자연휴양림", href: "/posts/055_백야자연휴양림.html" },
  { title: "백운산 자연휴양림", href: "/posts/057_백운산 자연휴양림.html" },
  { title: "변산 자연휴양림", href: "/posts/082_변산자연휴양림.html" },
  { title: "보현산자연휴양림", href: "/posts/058_보현산자연휴양림.html" },
  { title: "복주산 자연휴양림", href: "/posts/193_복주산 자연휴양림.html" },
  { title: "봉수산자연휴양림", href: "/posts/059_봉수산자연휴양림.html" },
  { title: "봉황자연휴양림", href: "/posts/060_봉황자연휴양림.html" },
  { title: "불정자연휴양림", href: "/posts/061_불정자연휴양림.html" },
  { title: "붉은오름자연휴양림", href: "/posts/063_붉은오름자연휴양림.html" },
  { title: "비슬산자연휴양림", href: "/posts/064_비슬산자연휴양림.html" },
  { title: "비학산자연휴양림", href: "/posts/065_비학산자연휴양림.html" },
  { title: "사천 케이블카 자연휴양림", href: "/posts/069_사천 케이블카 자연휴양림.html" },
  { title: "산삼자연휴양림", href: "/posts/070_산삼자연휴양림.html" },
  { title: "산수유자연휴양림", href: "/posts/071_산수유자연휴양림.html" },
  { title: "산음 자연휴양림", href: "/posts/191_산음 자연휴양림.html" },
  { title: "산청한방자연휴양림", href: "/posts/072_산청한방자연휴양림.html" },
  { title: "삼복자연휴양림(구둔내)", href: "/posts/224_삼복자연휴양림(구둔내).html" },
  { title: "삼봉 자연휴양림", href: "/posts/192_삼봉 자연휴양림.html" },
  { title: "삼척활기자연휴양림", href: "/posts/073_삼척활기자연휴양림.html" },
  { title: "상당산성 자연휴양림", href: "/posts/190_상당산성 자연휴양림.html" },
  { title: "생거진천자연휴양림", href: "/posts/074_생거진천자연휴양림.html" },
  { title: "서귀포자연휴양림", href: "/posts/075_서귀포자연휴양림.html" },
  { title: "서대산약용자연휴양림", href: "/posts/100_서대산약용자연휴양림.html" },
  { title: "서운산자연휴양림", href: "/posts/076_서운산자연휴양림.html" },
  { title: "석모도자연휴양림", href: "/posts/077_석모도자연휴양림.html" },
  { title: "성불산자연휴양림", href: "/posts/078_성불산자연휴양림.html" },
  { title: "성수산왕의숲자연휴양림", href: "/posts/079_성수산왕의숲자연휴양림.html" },
  { title: "성주봉자연휴양림", href: "/posts/080_성주봉자연휴양림.html" },
  { title: "성주산자연휴양림", href: "/posts/081_성주산자연휴양림.html" },
  { title: "세심자연휴양림", href: "/posts/083_세심자연휴양림.html" },
  { title: "소백산자연휴양림", href: "/posts/084_소백산자연휴양림.html" },
  { title: "소선암자연휴양림", href: "/posts/085_소선암자연휴양림.html" },
  { title: "속리산 말티재자연휴양림", href: "/posts/189_속리산 말티재자연휴양림.html" },
  { title: "속리산숲체험휴양마을", href: "/posts/088_속리산숲체험휴양마을.html" },
  { title: "송이밸리자연휴양림", href: "/posts/089_송이밸리자연휴양림.html" },
  { title: "송정자연휴양림", href: "/posts/090_송정자연휴양림.html" },
  { title: "수도산자연휴양림", href: "/posts/091_수도산자연휴양림.html" },
  { title: "수락산 동막골 자연휴양림", href: "/posts/187_수락산 동막골 자연휴양림.html" },
  { title: "수레의산자연휴양림", href: "/posts/092_수레의산자연휴양림.html" },
  { title: "순천자연휴양림", href: "/posts/093_순천자연휴양림.html" },
  { title: "숲체원", href: "/posts/094_숲체원.html" },
  { title: "신불산 자연휴양림", href: "/posts/188_신불산 자연휴양림.html" },
  { title: "신시도자연휴양림", href: "/posts/096_신시도자연휴양림.html" },
  { title: "신안자연휴양관", href: "/posts/097_신안자연휴양관.html" },
  { title: "신암저수지 숲속야영장", href: "/posts/186_신암저수지 숲속야영장.html" },
  { title: "심천치유자연휴양림", href: "/posts/098_심천치유자연휴양림.html" },
  { title: "아세안 자연휴양림", href: "/posts/099_아세안 자연휴양림.html" },
  { title: "안동호반자연휴양림", href: "/posts/101_안동호반자연휴양림.html" },
  { title: "안면도자연휴양림", href: "/posts/102_안면도자연휴양림.html" },
  { title: "안인진임해자연휴양림", href: "/posts/222_안인진임해자연휴양림.html" },
  { title: "양을산산림욕장", href: "/posts/103_양을산산림욕장.html" },
  { title: "양촌자연휴양림", href: "/posts/105_양촌자연휴양림.html" },
  { title: "양평 백운봉 자연휴양림", href: "/posts/185_양평 백운봉 자연휴양림.html" },
  { title: "양평설매재자연휴양림", href: "/posts/106_양평설매재자연휴양림.html" },
  { title: "양평쉬자파크", href: "/posts/107_양평쉬자파크.html" },
  { title: "여수봉황산자연휴양림", href: "/posts/108_여수봉황산자연휴양림.html" },
  { title: "영양에코둥지", href: "/posts/183_영양에코둥지.html" },
  { title: "영인산 자연휴양림", href: "/posts/184_영인산 자연휴양림.html" },
  { title: "오도산자연휴양림", href: "/posts/113_오도산자연휴양림.html" },
  { title: "오서산 자연휴양림", href: "/posts/114_오서산 자연휴양림.html" },
  { title: "옥성자연휴양림", href: "/posts/115_옥성자연휴양림.html" },
  { title: "옥전자연휴양림", href: "/posts/116_옥전자연휴양림.html" },
  { title: "옥화자연휴양림", href: "/posts/117_옥화자연휴양림.html" },
  { title: "와룡자연휴양림", href: "/posts/118_와룡자연휴양림.html" },
  { title: "용궐산자연휴양림", href: "/posts/219_용궐산자연휴양림.html" },
  { title: "용대 자연휴양림", href: "/posts/119_용대 자연휴양림.html" },
  { title: "용문산자연휴양림", href: "/posts/220_용문산자연휴양림.html" },
  { title: "용봉산자연휴양림", href: "/posts/120_용봉산자연휴양림.html" },
  { title: "용인자연휴양림", href: "/posts/121_용인자연휴양림.html" },
  { title: "용지봉 자연휴양림", href: "/posts/122_용지봉 자연휴양림.html" },
  { title: "용추자연휴양림", href: "/posts/123_용추자연휴양림.html" },
  { title: "용현 자연휴양림", href: "/posts/124_용현 자연휴양림.html" },
  { title: "용화산 자연휴양림", href: "/posts/125_용화산 자연휴양림.html" },
  { title: "운문산 자연휴양림", href: "/posts/126_운문산 자연휴양림.html" },
  { title: "운악산 자연휴양림", href: "/posts/127_운악산 자연휴양림.html" },
  { title: "운장산 자연휴양림", href: "/posts/128_운장산 자연휴양림.html" },
  { title: "운주산승마자연휴양림", href: "/posts/129_운주산승마자연휴양림.html" },
  { title: "원동자연휴양림(양산)", href: "/posts/221_원동자연휴양림(양산).html" },
  { title: "유명산 자연휴양림", href: "/posts/130_유명산 자연휴양림.html" },
  { title: "유치자연휴양림", href: "/posts/212_유치자연휴양림.html" },
  { title: "의왕바라산자연휴양림", href: "/posts/131_의왕바라산자연휴양림.html" },
  { title: "임해자연휴양림", href: "/posts/132_임해자연휴양림.html" },
  { title: "입화산 자연휴양림", href: "/posts/216_입화산 자연휴양림.html" },
  { title: "자굴산 자연휴양림", href: "/posts/133_자굴산 자연휴양림.html" },
  { title: "장령산자연휴양림", href: "/posts/134_장령산자연휴양림.html" },
  { title: "장태산자연휴양림", href: "/posts/135_장태산자연휴양림.html" },
  { title: "장항송림자연휴양림", href: "/posts/218_장항송림자연휴양림.html" },
  { title: "장흥 자연휴양림", href: "/posts/211_장흥 자연휴양림.html" },
  { title: "전라남도 완도자연휴양림", href: "/posts/136_전라남도 완도자연휴양림.html" },
  { title: "제암산자연휴양림", href: "/posts/137_제암산자연휴양림.html" },
  { title: "제주절물자연휴양림", href: "/posts/138_제주절물자연휴양림.html" },
  { title: "조령산 자연휴양림", href: "/posts/139_조령산 자연휴양림.html" },
  { title: "좌구산휴양랜드", href: "/posts/140_좌구산휴양랜드.html" },
  { title: "주작산자연휴양림", href: "/posts/141_주작산자연휴양림.html" },
  { title: "주천강자연휴양림", href: "/posts/217_주천강자연휴양림.html" },
  { title: "중미산 자연휴양림", href: "/posts/142_중미산 자연휴양림.html" },
  { title: "중산자연휴양림", href: "/posts/143_중산자연휴양림.html" },
  { title: "지리산 자연휴양림", href: "/posts/144_지리산 자연휴양림.html" },
  { title: "진도 자연휴양림", href: "/posts/145_진도 자연휴양림.html" },
  { title: "진산자연휴양림", href: "/posts/214_진산자연휴양림.html" },
  { title: "진주 월아산 자연휴양림", href: "/posts/146_진주 월아산 자연휴양림.html" },
  { title: "집다리골자연휴양림", href: "/posts/147_집다리골자연휴양림.html" },
  { title: "천관산 자연휴양림", href: "/posts/148_천관산 자연휴양림.html" },
  { title: "천보산 자연휴양림", href: "/posts/149_천보산 자연휴양림.html" },
  { title: "철원 두루웰 숲속문화촌", href: "/posts/150_철원 두루웰 숲속문화촌.html" },
  { title: "청도자연휴양림", href: "/posts/151_청도자연휴양림.html" },
  { title: "청송자연휴양림", href: "/posts/152_청송자연휴양림.html" },
  { title: "청옥산 자연휴양림", href: "/posts/153_청옥산 자연휴양림.html" },
  { title: "청태산 자연휴양림", href: "/posts/154_청태산 자연휴양림.html" },
  { title: "청평자연휴양림", href: "/posts/155_청평자연휴양림.html" },
  { title: "축령산자연휴양림", href: "/posts/156_축령산자연휴양림.html" },
  { title: "춘천숲자연휴양림", href: "/posts/157_춘천숲자연휴양림.html" },
  { title: "충북알프스자연휴양림", href: "/posts/158_충북알프스자연휴양림.html" },
  { title: "치악산자연휴양림", href: "/posts/159_치악산자연휴양림.html" },
  { title: "칠갑산자연휴양림", href: "/posts/160_칠갑산자연휴양림.html" },
  { title: "칠보산 자연휴양림", href: "/posts/161_칠보산 자연휴양림.html" },
  { title: "칼봉산자연휴양림", href: "/posts/162_칼봉산자연휴양림.html" },
  { title: "태백고원자연휴양림", href: "/posts/163_태백고원자연휴양림.html" },
  { title: "태학산자연휴양림", href: "/posts/164_태학산자연휴양림.html" },
  { title: "토함산자연휴양림", href: "/posts/165_토함산자연휴양림.html" },
  { title: "통고산 자연휴양림", href: "/posts/166_통고산 자연휴양림.html" },
  { title: "팔공산금화자연휴양림", href: "/posts/167_팔공산금화자연휴양림.html" },
  { title: "팔영산자연휴양림", href: "/posts/168_팔영산자연휴양림.html" },
  { title: "평창자연휴양림", href: "/posts/169_평창자연휴양림.html" },
  { title: "피노키오자연휴양림", href: "/posts/170_피노키오자연휴양림.html" },
  { title: "하동편백자연휴양림", href: "/posts/171_하동편백자연휴양림.html" },
  { title: "하추자연휴양림", href: "/posts/172_하추자연휴양림.html" },
  { title: "학가산우래자연휴양림", href: "/posts/173_학가산우래자연휴양림.html" },
  { title: "한천자연휴양림", href: "/posts/174_한천자연휴양림.html" },
  { title: "함평자연생태공원", href: "/posts/215_함평자연생태공원.html" },
  { title: "화왕산자연휴양림", href: "/posts/175_화왕산자연휴양림.html" },
  { title: "화원자연휴양림", href: "/posts/176_화원자연휴양림.html" },
  { title: "화천숲속 야영장", href: "/posts/177_화천숲속 야영장.html" },
  { title: "황정산 자연휴양림", href: "/posts/178_황정산 자연휴양림.html" },
  { title: "회문산 자연휴양림", href: "/posts/179_회문산 자연휴양림.html" },
  { title: "횡성자연휴양림", href: "/posts/180_횡성자연휴양림.html" },
  { title: "흑석산자연휴양림", href: "/posts/181_흑석산자연휴양림.html" },
  { title: "흥부골자연휴양림", href: "/posts/213_흥부골자연휴양림.html" },
  { title: "희리산 자연휴양림", href: "/posts/182_희리산 자연휴양림.html" },
];
