export type Post = { title: string; href: string };

export const POSTS: Post[] = [
  { title: "가리왕산자연휴양림", href: "/posts/001_가리왕산자연휴양림.html" },
  { title: "가야산 자연휴양림", href: "/posts/002_가야산 자연휴양림.html" },
  { title: "가평자연휴양림", href: "/posts/003_가평자연휴양림.html" },
  { title: "강선계곡자연휴양림", href: "/posts/004_강선계곡자연휴양림.html" },
  { title: "강천산 자연휴양림", href: "/posts/005_강천산 자연휴양림.html" },
  { title: "건청봉 자연휴양림", href: "/posts/006_건청봉 자연휴양림.html" },
  { title: "경주자연휴양림", href: "/posts/007_경주자연휴양림.html" },
  { title: "계곡자연휴양림", href: "/posts/008_계곡자연휴양림.html" },
  { title: "계양산자연휴양림", href: "/posts/009_계양산자연휴양림.html" },
  { title: "고로쇠약수자연휴양림", href: "/posts/010_고로쇠약수자연휴양림.html" },
  { title: "고운산자연휴양림", href: "/posts/011_고운산자연휴양림.html" },
  { title: "고장산자연휴양림", href: "/posts/012_고장산자연휴양림.html" },
  { title: "고창자연휴양림", href: "/posts/013_고창자연휴양림.html" },
  { title: "곡성자연휴양림", href: "/posts/014_곡성자연휴양림.html" },
  { title: "관산자연휴양림", href: "/posts/015_관산자연휴양림.html" },
  { title: "관악산자연휴양림", href: "/posts/016_관악산자연휴양림.html" },
  { title: "광덕산 자연휴양림", href: "/posts/017_광덕산 자연휴양림.html" },
  { title: "광천자연휴양림", href: "/posts/018_광천자연휴양림.html" },
  { title: "괘방산 자연휴양림", href: "/posts/019_괘방산 자연휴양림.html" },
  { title: "구론봉자연휴양림", href: "/posts/020_구론봉자연휴양림.html" },
  { title: "구룡산자연휴양림", href: "/posts/021_구룡산자연휴양림.html" },
  { title: "구봉산자연휴양림", href: "/posts/022_구봉산자연휴양림.html" },
  { title: "국사봉자연휴양림", href: "/posts/023_국사봉자연휴양림.html" },
  { title: "권금성자연휴양림", href: "/posts/024_권금성자연휴양림.html" },
  { title: "금산자연휴양림", href: "/posts/025_금산자연휴양림.html" },
  { title: "금수산자연휴양림", href: "/posts/026_금수산자연휴양림.html" },
  { title: "금원산자연휴양림", href: "/posts/027_금원산자연휴양림.html" },
  { title: "기백산자연휴양림", href: "/posts/028_기백산자연휴양림.html" },
  { title: "까치산자연휴양림", href: "/posts/029_까치산자연휴양림.html" },
  { title: "나래숲자연휴양림", href: "/posts/030_나래숲자연휴양림.html" },
  { title: "남산자연휴양림", href: "/posts/031_남산자연휴양림.html" },
  { title: "내성천자연휴양림", href: "/posts/032_내성천자연휴양림.html" },
  { title: "내장산 자연휴양림", href: "/posts/033_내장산 자연휴양림.html" },
  { title: "노령산자연휴양림", href: "/posts/034_노령산자연휴양림.html" },
  { title: "노추산자연휴양림", href: "/posts/035_노추산자연휴양림.html" },
  { title: "대관령 자연휴양림", href: "/posts/036_대관령 자연휴양림.html" },
  { title: "대미산자연휴양림", href: "/posts/037_대미산자연휴양림.html" },
  { title: "대성산자연휴양림", href: "/posts/038_대성산자연휴양림.html" },
  { title: "대야산 자연휴양림", href: "/posts/039_대야산 자연휴양림.html" },
  { title: "대운산자연휴양림", href: "/posts/040_대운산자연휴양림.html" },
  { title: "도명산자연휴양림", href: "/posts/041_도명산자연휴양림.html" },
  { title: "도삼산자연휴양림", href: "/posts/042_도삼산자연휴양림.html" },
  { title: "도화자연휴양림", href: "/posts/043_도화자연휴양림.html" },
  { title: "독용산자연휴양림", href: "/posts/044_독용산자연휴양림.html" },
  { title: "돈수암자연휴양림", href: "/posts/045_돈수암자연휴양림.html" },
  { title: "동래자연휴양림", href: "/posts/046_동래자연휴양림.html" },
  { title: "동악산자연휴양림", href: "/posts/047_동악산자연휴양림.html" },
  { title: "두릉산자연휴양림", href: "/posts/048_두릉산자연휴양림.html" },
  { title: "두류산자연휴양림", href: "/posts/049_두류산자연휴양림.html" },
  { title: "두문자연휴양림", href: "/posts/050_두문자연휴양림.html" },
  { title: "두승산 자연휴양림", href: "/posts/051_두승산 자연휴양림.html" },
  { title: "두악산자연휴양림", href: "/posts/052_두악산자연휴양림.html" },
  { title: "두정산자연휴양림", href: "/posts/053_두정산자연휴양림.html" },
  { title: "등용산자연휴양림", href: "/posts/054_등용산자연휴양림.html" },
  { title: "리조트형 자연휴양림", href: "/posts/055_리조트형 자연휴양림.html" },
  { title: "마곡사 자연휴양림", href: "/posts/056_마곡사 자연휴양림.html" },
  { title: "만장굴자연휴양림", href: "/posts/057_만장굴자연휴양림.html" },
  { title: "명성산자연휴양림", href: "/posts/058_명성산자연휴양림.html" },
  { title: "명지산자연휴양림", href: "/posts/059_명지산자연휴양림.html" },
  { title: "무장산자연휴양림", href: "/posts/060_무장산자연휴양림.html" },
  { title: "무학산자연휴양림", href: "/posts/061_무학산자연휴양림.html" },
  { title: "문경자연휴양림", href: "/posts/062_문경자연휴양림.html" },
  { title: "문주산자연휴양림", href: "/posts/063_문주산자연휴양림.html" },
  { title: "미숙산자연휴양림", href: "/posts/064_미숙산자연휴양림.html" },
  { title: "미시령 자연휴양림", href: "/posts/065_미시령 자연휴양림.html" },
  { title: "미천골자연휴양림", href: "/posts/066_미천골자연휴양림.html" },
  { title: "미팔봉자연휴양림", href: "/posts/067_미팔봉자연휴양림.html" },
  { title: "민주지산자연휴양림", href: "/posts/068_민주지산자연휴양림.html" },
  { title: "백동산자연휴양림", href: "/posts/069_백동산자연휴양림.html" },
  { title: "백석산자연휴양림", href: "/posts/070_백석산자연휴양림.html" },
  { title: "백암산자연휴양림", href: "/posts/071_백암산자연휴양림.html" },
  { title: "백화산자연휴양림", href: "/posts/072_백화산자연휴양림.html" },
  { title: "뱀재자연휴양림", href: "/posts/073_뱀재자연휴양림.html" },
  { title: "보덕산자연휴양림", href: "/posts/074_보덕산자연휴양림.html" },
  { title: "보령자연휴양림", href: "/posts/075_보령자연휴양림.html" },
  { title: "보룡산자연휴양림", href: "/posts/076_보룡산자연휴양림.html" },
  { title: "보한산자연휴양림", href: "/posts/077_보한산자연휴양림.html" },
  { title: "봉두산자연휴양림", href: "/posts/078_봉두산자연휴양림.html" },
  { title: "봉감자연휴양림", href: "/posts/079_봉감자연휴양림.html" },
  { title: "봉학산자연휴양림", href: "/posts/080_봉학산자연휴양림.html" },
  { title: "봉화자연휴양림", href: "/posts/081_봉화자연휴양림.html" },
  { title: "부안자연휴양림", href: "/posts/082_부안자연휴양림.html" },
  { title: "부귀산자연휴양림", href: "/posts/083_부귀산자연휴양림.html" },
  { title: "부남산자연휴양림", href: "/posts/084_부남산자연휴양림.html" },
  { title: "부용산자연휴양림", href: "/posts/085_부용산자연휴양림.html" },
  { title: "북한산 자연휴양림", href: "/posts/086_북한산 자연휴양림.html" },
  { title: "분발산자연휴양림", href: "/posts/087_분발산자연휴양림.html" },
  { title: "불암산자연휴양림", href: "/posts/088_불암산자연휴양림.html" },
  { title: "비봉산자연휴양림", href: "/posts/089_비봉산자연휴양림.html" },
  { title: "사량산 자연휴양림", href: "/posts/090_사량산 자연휴양림.html" },
  { title: "산청자연휴양림", href: "/posts/091_산청자연휴양림.html" },
  { title: "삼각산자연휴양림", href: "/posts/092_삼각산자연휴양림.html" },
  { title: "삼봉산자연휴양림", href: "/posts/093_삼봉산자연휴양림.html" },
  { title: "삼악산 자연휴양림", href: "/posts/094_삼악산 자연휴양림.html" },
  { title: "삼을재자연휴양림", href: "/posts/095_삼을재자연휴양림.html" },
  { title: "삼죽산자연휴양림", href: "/posts/096_삼죽산자연휴양림.html" },
  { title: "삼태산자연휴양림", href: "/posts/097_삼태산자연휴양림.html" },
  { title: "상동자연휴양림", href: "/posts/098_상동자연휴양림.html" },
  { title: "상희자연휴양림", href: "/posts/099_상희자연휴양림.html" },
  { title: "서대산 자연휴양림", href: "/posts/100_서대산 자연휴양림.html" },
  { title: "서시산자연휴양림", href: "/posts/101_서시산자연휴양림.html" },
  { title: "서악산자연휴양림", href: "/posts/102_서악산자연휴양림.html" },
  { title: "선인봉자연휴양림", href: "/posts/103_선인봉자연휴양림.html" },
  { title: "설악산 자연휴양림", href: "/posts/104_설악산 자연휴양림.html" },
  { title: "성산자연휴양림", href: "/posts/105_성산자연휴양림.html" },
  { title: "성주자연휴양림", href: "/posts/106_성주자연휴양림.html" },
  { title: "성호산자연휴양림", href: "/posts/107_성호산자연휴양림.html" },
  { title: "세봉산자연휴양림", href: "/posts/108_세봉산자연휴양림.html" },
  { title: "오도산자연휴양림", href: "/posts/113_오도산자연휴양림.html" },
  { title: "오서산 자연휴양림", href: "/posts/114_오서산 자연휴양림.html" },
  { title: "옥성자연휴양림", href: "/posts/115_옥성자연휴양림.html" },
  { title: "옥전자연휴양림", href: "/posts/116_옥전자연휴양림.html" },
  { title: "옥화자연휴양림", href: "/posts/117_옥화자연휴양림.html" },
  { title: "와룡자연휴양림", href: "/posts/118_와룡자연휴양림.html" },
  { title: "용대 자연휴양림", href: "/posts/119_용대 자연휴양림.html" },
  { title: "용봉산자연휴양림", href: "/posts/120_용봉산자연휴양림.html" },
  { title: "용인자연휴양림", href: "/posts/121_용인자연휴양림.html" },
  { title: "용지봉 자연휴양림", href: "/posts/122_용지봉 자연휴양림.html" },
  { title: "용추자연휴양림", href: "/posts/123_용추자연휴양림.html" },
  { title: "용현 자연휴양림", href: "/posts/124_용현 자연휴양림.html" },
  { title: "용화산 자연휴양림", href: "/posts/125_용화산 자연휴양림.html" },
  { title: "운문산 자연휴양림", href: "/posts/126_운문산 자연휴양림.html" },
  { title: "운악산 자연휴양림", href: "/posts/127_운악산 자연휴양림.html" },
  { title: "운장산 자연휴양림", href: "/posts/128_운장산 자연휴양림.html" },
  { title: "운주산승마자연휴양림", href: "/posts/129_운주산승마자연휴양림.html" },
  { title: "유명산 자연휴양림", href: "/posts/130_유명산 자연휴양림.html" },
  { title: "의왕바라산자연휴양림", href: "/posts/131_의왕바라산자연휴양림.html" },
  { title: "임해자연휴양림", href: "/posts/132_임해자연휴양림.html" },
  { title: "자굴산 자연휴양림", href: "/posts/133_자굴산 자연휴양림.html" },
  { title: "장령산자연휴양림", href: "/posts/134_장령산자연휴양림.html" },
  { title: "장태산자연휴양림", href: "/posts/135_장태산자연휴양림.html" },
  { title: "전라남도 완도자연휴양림", href: "/posts/136_전라남도 완도자연휴양림.html" },
  { title: "제암산자연휴양림", href: "/posts/137_제암산자연휴양림.html" },
  { title: "제주절물자연휴양림", href: "/posts/138_제주절물자연휴양림.html" },
  { title: "조령산 자연휴양림", href: "/posts/139_조령산 자연휴양림.html" },
  { title: "좌구산휴양랜드", href: "/posts/140_좌구산휴양랜드.html" },
  { title: "주작산자연휴양림", href: "/posts/141_주작산자연휴양림.html" },
  { title: "중미산 자연휴양림", href: "/posts/142_중미산 자연휴양림.html" },
  { title: "중산자연휴양림", href: "/posts/143_중산자연휴양림.html" },
  { title: "지리산 자연휴양림", href: "/posts/144_지리산 자연휴양림.html" },
  { title: "진도 자연휴양림", href: "/posts/145_진도 자연휴양림.html" },
  { title: "진주 월아산 자연휴양림", href: "/posts/146_진주 월아산 자연휴양림.html" },
  { title: "집다리골자연휴양림", href: "/posts/147_집다리골자연휴양림.html" },
  { title: "천관산 자연휴양림", href: "/posts/148_천관산 자연휴양림.html" },
  { title: "천보산 자연휴양림", href: "/posts/149_천보산 자연휴양림.html" },
  { title: "철원 두루웰 숲속문화촌", href: "/posts/150_철원 두루웰 숲속문화촌.html" },
  { title: "청도자연휴양림", href: "/posts/151_청도자연휴양림.html" },
  { title: "청송자연휴양림", href: "/posts/152_청송자연휴양림.html" },
  { title: "청옥산 자연휴양림", href: "/posts/153_청옥산 자연휴양림.html" },
  { title: "청태산 자연휴양림", href: "/posts/154_청태산 자연휴양림.html" },
  { title: "청평자연휴양림", href: "/posts/155_청평자연휴양림.html" },
  { title: "축령산자연휴양림", href: "/posts/156_축령산자연휴양림.html" },
  { title: "춘천숲자연휴양림", href: "/posts/157_춘천숲자연휴양림.html" },
  { title: "충북알프스자연휴양림", href: "/posts/158_충북알프스자연휴양림.html" },
  { title: "치악산자연휴양림", href: "/posts/159_치악산자연휴양림.html" },
  { title: "칠갑산자연휴양림", href: "/posts/160_칠갑산자연휴양림.html" },
  { title: "칠보산 자연휴양림", href: "/posts/161_칠보산 자연휴양림.html" },
  { title: "칼봉산자연휴양림", href: "/posts/162_칼봉산자연휴양림.html" },
  { title: "태백고원자연휴양림", href: "/posts/163_태백고원자연휴양림.html" },
  { title: "태학산자연휴양림", href: "/posts/164_태학산자연휴양림.html" },
  { title: "토함산자연휴양림", href: "/posts/165_토함산자연휴양림.html" },
  { title: "통고산 자연휴양림", href: "/posts/166_통고산 자연휴양림.html" },
  { title: "팔공산금화자연휴양림", href: "/posts/167_팔공산금화자연휴양림.html" },
  { title: "팔영산자연휴양림", href: "/posts/168_팔영산자연휴양림.html" },
  { title: "평창자연휴양림", href: "/posts/169_평창자연휴양림.html" },
  { title: "피노키오자연휴양림", href: "/posts/170_피노키오자연휴양림.html" },
  { title: "하동편백자연휴양림", href: "/posts/171_하동편백자연휴양림.html" },
  { title: "하추자연휴양림", href: "/posts/172_하추자연휴양림.html" },
  { title: "학가산우래자연휴양림", href: "/posts/173_학가산우래자연휴양림.html" },
  { title: "한천자연휴양림", href: "/posts/174_한천자연휴양림.html" },
  { title: "화왕산자연휴양림", href: "/posts/175_화왕산자연휴양림.html" },
  { title: "화원자연휴양림", href: "/posts/176_화원자연휴양림.html" },
  { title: "화천숲속 야영장", href: "/posts/177_화천숲속 야영장.html" },
  { title: "황정산 자연휴양림", href: "/posts/178_황정산 자연휴양림.html" },
  { title: "회문산 자연휴양림", href: "/posts/179_회문산 자연휴양림.html" },
  { title: "횡성자연휴양림", href: "/posts/180_횡성자연휴양림.html" },
  { title: "흑석산자연휴양림", href: "/posts/181_흑석산자연휴양림.html" },
  { title: "희리산 자연휴양림", href: "/posts/182_희리산 자연휴양림.html" },
];
